// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/repository/user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	boundary "ApiMarketplace/internal/boundary"
	domain "ApiMarketplace/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user *domain.RegisterUserDb) (*boundary.RegisterUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*boundary.RegisterUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// LoginByUsername mocks base method.
func (m *MockUserRepository) LoginByUsername(ctx context.Context, username *domain.LoginUserDb) (*domain.LoginUserResponseDb, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.LoginUserResponseDb)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginByUsername indicates an expected call of LoginByUsername.
func (mr *MockUserRepositoryMockRecorder) LoginByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginByUsername", reflect.TypeOf((*MockUserRepository)(nil).LoginByUsername), ctx, username)
}
