// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/repository/ads.go

// Package mocks is a generated GoMock package.
package mocks

import (
	boundary "ApiMarketplace/internal/boundary"
	domain "ApiMarketplace/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAdsRepository is a mock of AdsRepository interface.
type MockAdsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdsRepositoryMockRecorder
}

// MockAdsRepositoryMockRecorder is the mock recorder for MockAdsRepository.
type MockAdsRepositoryMockRecorder struct {
	mock *MockAdsRepository
}

// NewMockAdsRepository creates a new mock instance.
func NewMockAdsRepository(ctrl *gomock.Controller) *MockAdsRepository {
	mock := &MockAdsRepository{ctrl: ctrl}
	mock.recorder = &MockAdsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdsRepository) EXPECT() *MockAdsRepositoryMockRecorder {
	return m.recorder
}

// CreateAds mocks base method.
func (m *MockAdsRepository) CreateAds(ctx context.Context, adsData *domain.CreateAdsDb) (*boundary.CreateAdsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAds", ctx, adsData)
	ret0, _ := ret[0].(*boundary.CreateAdsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAds indicates an expected call of CreateAds.
func (mr *MockAdsRepositoryMockRecorder) CreateAds(ctx, adsData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAds", reflect.TypeOf((*MockAdsRepository)(nil).CreateAds), ctx, adsData)
}

// GetAdsList mocks base method.
func (m *MockAdsRepository) GetAdsList(ctx context.Context, adsListData *domain.AdsListDb) ([]*domain.AdsListResponseDb, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdsList", ctx, adsListData)
	ret0, _ := ret[0].([]*domain.AdsListResponseDb)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAdsList indicates an expected call of GetAdsList.
func (mr *MockAdsRepositoryMockRecorder) GetAdsList(ctx, adsListData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdsList", reflect.TypeOf((*MockAdsRepository)(nil).GetAdsList), ctx, adsListData)
}
